export const specialties = [
  'Bipolar',
  'LGBTQ',
  'Medication/Prescribing',
  'Suicide History/Attempts',
  'General Mental Health (anxiety, depression, stress, grief, life transitions)',
  "Men's issues",
  'Relationship Issues (family, friends, couple, etc)',
  'Trauma & PTSD',
  'Personality disorders',
  'Personal growth',
  'Substance use/abuse',
  'Pediatrics',
  "Women's issues (post-partum, infertility, family planning)",
  'Chronic pain',
  'Weight loss & nutrition',
  'Eating disorders',
  'Diabetic Diet and nutrition',
  'Coaching (leadership, career, academic and wellness)',
  'Life coaching',
  'Obsessive-compulsive disorders',
  'Neuropsychological evaluations & testing (ADHD testing)',
  'Attention and Hyperactivity (ADHD)',
  'Sleep issues',
  'Schizophrenia and psychotic disorders',
  'Learning disorders',
  'Domestic abuse',
]

export const tagColors = [
  '#FF6F61',
  '#6B5B95',
  '#88B04B',
  '#92A8D1',
  '#955251',
  '#B565A7',
  '#009B77',
  '#DD4124',
  '#45B8AC',
  '#EFC050',
  '#5B5EA6',
  '#9B2335',
  '#DFCFBE',
  '#BC243C',
  '#98B4D4',
  '#C3447A',
  '#C32148',
  '#FF8C42',
  '#008B8B',
  '#FF6347',
  '#00BFFF',
  '#DC143C',
  '#FF4500',
  '#9932CC',
  '#1E90FF',
  '#C71585',
  '#2E8B57',
]
